var missions_info = [
  {
    "category": "FUN 趣味",
    "condition": "錄影並上傳影片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "中午12點在野台播音樂並跳舞15秒（舞蹈類型不限）",
    "description-in": "中午12點在野台播音樂並跳舞15秒（舞蹈類型不限）",
    "hardness": "普通（10分）",
    "hashtag": "#NTHUGO001",
    "id": "NTHUGO001",
    "img": "img/portfolio/001.jpg",
    "img-in": "img/portfolio/001.jpg",
    "title": "show your body"
  },
  {
    "category": "FUN 趣味",
    "condition": "截圖第三十秒時的直播畫面並上傳圖片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上，我們會至你的個人頁面查看是否在同一帳號上開直播",
    "description": "開直播在30秒內獲得0人觀看中並截圖（任務已終止）",
    "description-in": "開直播在30秒內獲得0人觀看中並截圖（因「只限本人」情形嚴重，任務已終止）(5/4晚間八點前上傳者仍會計分10分)",
    "hardness": "任務終止（0分）",
    "hashtag": "#NTHUGO002",
    "id": "NTHUGO002",
    "img": "img/portfolio/002.jpg",
    "img-in": "img/portfolio/002.jpg",
    "title": "極度邊緣"
  },
  {
    "category": "FUN 趣味",
    "condition": "錄影並上傳影片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "找到五個人一起唱FLY OUT",
    "description-in": "找到五個人一起唱FLY OUT",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO003",
    "id": "NTHUGO003",
    "img": "img/portfolio/003.jpg",
    "img-in": "img/portfolio/003.jpg",
    "title": "清大八嘎冏"
  },
  {
    "category": "FUN 趣味",
    "condition": "錄影並上傳影片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "從校門跑到小吃部:\"我的男/女朋友怎麼迷路還不來找我\"",
    "description-in": "邊喊「我的男/女朋友怎麼迷路還不來找我」邊從校門口跑到小吃部",
    "hardness": "困難（15分）",
    "hashtag": "#NTHUGO004",
    "id": "NTHUGO004",
    "img": "img/portfolio/004.jpg",
    "img-in": "img/portfolio/004.jpg",
    "title": "摳年沒人愛"
  },
  {
    "category": "FUN 趣味",
    "condition": "發文頁面及發文讚數達標後各截一次圖，並將截圖私訊粉專",
    "description": "在靠北清大／竹大獲得87讚",
    "description-in": "在靠北清大／竹大獲得87讚",
    "hardness": "普通（10分）",
    "hashtag": "#NTHUGO005",
    "id": "NTHUGO005",
    "img": "img/portfolio/005.jpg",
    "img-in": "img/portfolio/005.jpg",
    "title": "哩金靠北"
  },
  {
    "category": "FUN 趣味",
    "condition": "錄影並上傳影片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "跟路人說：「你長得好像我下一任男/女友」",
    "description-in": "跟路人說：「你長得好像我下一任男/女友」",
    "hardness": "普通（10分）",
    "hashtag": "#NTHUGO006",
    "id": "NTHUGO006",
    "img": "img/portfolio/006.jpg",
    "img-in": "img/portfolio/006.jpg",
    "title": "路邊情人"
  },
  {
    "category": "FUN 趣味",
    "condition": "截圖並上傳圖片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "將臉書大頭貼換成清華大作戰並獲得50讚",
    "description-in": "將臉書大頭貼換成清華大作戰並獲得50讚",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO007",
    "id": "NTHUGO007",
    "img": "img/portfolio/007.jpg",
    "img-in": "img/portfolio/007.jpg",
    "title": "大作戰GOGOGO"
  },
  {
    "category": "FUN 趣味",
    "condition": "拍照並上傳照片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "找到三個穿著不同顏色清大帽T的人合照",
    "description-in": "找到三個穿著不同顏色清大帽T的人合照",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO008",
    "id": "NTHUGO008",
    "img": "img/portfolio/008.jpg",
    "img-in": "img/portfolio/008.jpg",
    "title": "帽T狂熱仔"
  },
  {
    "category": "FUN 趣味",
    "condition": "拍照並上傳照片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "找三對情侶合照",
    "description-in": "找三對情侶合照",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO009",
    "id": "NTHUGO009",
    "img": "img/portfolio/009.jpg",
    "img-in": "img/portfolio/009.jpg",
    "title": "就你沒有情人"
  },
  {
    "category": "ISSUE 議題",
    "condition": "留言在相簿下，截圖並上傳圖片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "閱讀張貼於粉專相簿的「買課事件懶人包」",
    "description-in": "閱讀張貼於粉專相簿的「買課事件懶人包」，並在相簿留言處回覆相簿描述裡的問題。",
    "hardness": "困難（15分）",
    "hashtag": "#NTHUGO010",
    "id": "NTHUGO010",
    "img": "img/portfolio/010.jpg",
    "img-in": "img/portfolio/010.jpg",
    "title": "買課案件懶人包"
  },
  {
    "category": "ISSUE 議題",
    "condition": "發布貼文在自己的塗鴉牆，並將貼文連結發布至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "尋找與年金改革相關的資料並發表看法",
    "description-in": "尋找與年金改革相關的報導／文章／書籍／影片...，並發表你對此的看法",
    "hardness": "困難（15分）",
    "hashtag": "#NTHUGO011",
    "id": "NTHUGO011",
    "img": "img/portfolio/011.jpg",
    "img-in": "img/portfolio/011.jpg",
    "title": "年金改不改"
  },
  {
    "category": "FUN 趣味",
    "condition": "錄影並上傳影片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "找到一個夥伴以兩人三腳的方式從小吃部走到校門口",
    "description-in": "找到一個夥伴以兩人三腳的方式從小吃部走到校門口",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO012",
    "id": "NTHUGO012",
    "img": "img/portfolio/012.jpg",
    "img-in": "img/portfolio/012.jpg",
    "title": "2+2＝3"
  },
  {
    "category": "FUN 趣味",
    "condition": "錄影並上傳影片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "以匍匐前進的方式穿越旺宏穿堂",
    "description-in": "以匍匐前進的方式穿越旺宏穿堂",
    "hardness": "困難（15分）",
    "hashtag": "#NTHUGO013",
    "id": "NTHUGO013",
    "img": "img/portfolio/013.jpg",
    "img-in": "img/portfolio/013.jpg",
    "title": "五體投地"
  },
  {
    "category": "FUN 趣味",
    "condition": "拍照並上傳照片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上（本人與畫眉皆需完整入鏡）",
    "description": "擺出與畫眉一樣的表情姿勢合照",
    "description-in": "擺出與畫眉一樣的表情姿勢合照",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO014",
    "id": "NTHUGO014",
    "img": "img/portfolio/014.jpg",
    "img-in": "img/portfolio/014.jpg",
    "title": "睡眼惺忪"
  },
  {
    "category": "FUN 趣味",
    "condition": "拍照並上傳照片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "在頭髮上面剃NTHU",
    "description-in": "在頭髮上面剃NTHU",
    "hardness": "困難（15分）",
    "hashtag": "#NTHUGO015",
    "id": "NTHUGO015",
    "img": "img/portfolio/015.jpg",
    "img-in": "img/portfolio/015.jpg",
    "title": "頂著清華的榮耀"
  },
  {
    "category": "FUN 趣味",
    "condition": "錄影並上傳影片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "用五種不同的語言說我愛清大",
    "description-in": "用五種不同的語言說我愛清大",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO016",
    "id": "NTHUGO016",
    "img": "img/portfolio/016.jpg",
    "img-in": "img/portfolio/016.jpg",
    "title": "吾愛吾校"
  },
  {
    "category": "FUN 趣味",
    "condition": "錄影並上傳影片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "用五種語言說「我愛你」",
    "description-in": "用五種語言說「我愛你」",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO017",
    "id": "NTHUGO017",
    "img": "img/portfolio/017.jpg",
    "img-in": "img/portfolio/017.jpg",
    "title": "吾更愛你"
  },
  {
    "category": "FUN 趣味",
    "condition": "拍照並上傳照片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "蒐集五個穿著格子襯衫的人",
    "description-in": "蒐集五個穿著格子襯衫的人",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO018",
    "id": "NTHUGO018",
    "img": "img/portfolio/018.jpg",
    "img-in": "img/portfolio/018.jpg",
    "title": "格子控"
  },
  {
    "category": "FUN 趣味",
    "condition": "拍照並上傳照片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上，說明分別是哪些營隊",
    "description": "蒐集五個穿著不同營服的人",
    "description-in": "蒐集五個穿著不同營服的人",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO019",
    "id": "NTHUGO019",
    "img": "img/portfolio/019.jpg",
    "img-in": "img/portfolio/019.jpg",
    "title": "步步為營"
  },
  {
    "category": "FUN 趣味",
    "condition": "錄影並上傳影片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "對路人唱「自強自強」對方接出「行健不息需自強」",
    "description-in": "對路人唱「自強自強」對方接出「行健不息需自強」即成功",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO020",
    "id": "NTHUGO020",
    "img": "img/portfolio/020.jpg",
    "img-in": "img/portfolio/020.jpg",
    "title": "校歌你也懂？"
  },
  {
    "category": "FUN 趣味",
    "condition": "拍照並上傳照片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上。球球的粉專：https://www.facebook.com/wuchiuchiu/",
    "description": "到水漫跟球球合照（球球須看鏡頭）",
    "description-in": "到水漫跟球球合照（球球須看鏡頭）",
    "hardness": "普通（10分）",
    "hashtag": "#NTHUGO021",
    "id": "NTHUGO021",
    "img": "img/portfolio/021.jpg",
    "img-in": "img/portfolio/021.jpg",
    "title": "球你看我"
  },
  {
    "category": "FUN 趣味",
    "condition": "發文頁面及發文讚數達標後各截一次圖，並將截圖私訊粉專",
    "description": "在靠北清大／竹大獲得17讚",
    "description-in": "在靠北清大／竹大獲得17讚",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO022",
    "id": "NTHUGO022",
    "img": "img/portfolio/022.jpg",
    "img-in": "img/portfolio/022.jpg",
    "title": "17靠北"
  },
  {
    "category": "FUN 趣味",
    "condition": "截圖並上傳圖片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "臉書發佈10篇抽獎文",
    "description-in": "臉書發佈10篇抽獎文",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO023",
    "id": "NTHUGO023",
    "img": "img/portfolio/023.jpg",
    "img-in": "img/portfolio/023.jpg",
    "title": "永遠都不是我"
  },
  {
    "category": "FUN 趣味",
    "condition": "錄影並上傳影片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "30秒內爬完二一坡",
    "description-in": "30秒內爬完二一坡",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO024",
    "id": "NTHUGO024",
    "img": "img/portfolio/024.jpg",
    "img-in": "img/portfolio/024.jpg",
    "title": "清大閃電波特"
  },
  {
    "category": "FUN 趣味",
    "condition": "拍照並上傳照片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "假日時在清大校園內跟一個市民家庭合照",
    "description-in": "假日時在清大校園內跟一個市民家庭合照",
    "hardness": "普通（10分）",
    "hashtag": "#NTHUGO025",
    "id": "NTHUGO025",
    "img": "img/portfolio/025.jpg",
    "img-in": "img/portfolio/025.jpg",
    "title": "歡迎再來"
  },
  {
    "category": "FUN 趣味",
    "condition": "截圖並上傳圖片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "按清大畢業季、NTHU GO的粉絲專頁讚並設定搶先看",
    "description-in": "按清華大學畢業季＆清華大作戰 NTHU GO的粉絲專頁讚並設定搶先看",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO026",
    "id": "NTHUGO026",
    "img": "img/portfolio/026.jpg",
    "img-in": "img/portfolio/026.jpg",
    "title": "腦粉是我"
  },
  {
    "category": "FUN 趣味",
    "condition": "錄影並上傳影片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "上傳任一歌手的cover dance影片",
    "description-in": "上傳任一歌手的cover dance影片",
    "hardness": "困難（15分）",
    "hashtag": "#NTHUGO027",
    "id": "NTHUGO027",
    "img": "img/portfolio/027.jpg",
    "img-in": "img/portfolio/027.jpg",
    "title": "舞力全開"
  },
  {
    "category": "FUN 趣味",
    "condition": "截圖Dcard「我發表的文章」頁面並上傳圖片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "在Dcard上發一篇文獲得2000愛心",
    "description-in": "在Dcard上發一篇文獲得2000愛心",
    "hardness": "困難（15分）",
    "hashtag": "#NTHUGO028",
    "id": "NTHUGO028",
    "img": "img/portfolio/028.jpg",
    "img-in": "img/portfolio/028.jpg",
    "title": "不是創作文"
  },
  {
    "category": "FUN 趣味",
    "condition": "拍照並上傳照片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "到新竹動物園拍河馬張大嘴的樣子",
    "description-in": "到新竹動物園拍河馬張大嘴的樣子",
    "hardness": "普通（10分）",
    "hashtag": "#NTHUGO029",
    "id": "NTHUGO029",
    "img": "img/portfolio/029.jpg",
    "img-in": "img/portfolio/029.jpg",
    "title": "阿肥你好"
  },
  {
    "category": "FUN 趣味",
    "condition": "組圖至活動粉專頁面，分別為在清大以及火車站跟Ubike合照（需拍到腳踏車編號）",
    "description": "從清大騎Ubike到火車站",
    "description-in": "從清大騎Ubike到火車站",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO030",
    "id": "NTHUGO030",
    "img": "img/portfolio/030.jpg",
    "img-in": "img/portfolio/030.jpg",
    "title": "浪費人生"
  },
  {
    "category": "FUN 趣味",
    "condition": "錄影並上傳影片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "在笨鳥（黑冠麻鷺）旁邊學牠走路",
    "description-in": "在笨鳥（黑冠麻鷺）旁邊學牠走路",
    "hardness": "困難（15分）",
    "hashtag": "#NTHUGO031",
    "id": "NTHUGO031",
    "img": "img/portfolio/031.jpg",
    "img-in": "img/portfolio/031.jpg",
    "title": "笨鳥慢飛"
  },
  {
    "category": "FUN 趣味",
    "condition": "錄影並上傳影片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上（成功與否不重要，重要的是你嘗試過了XD）",
    "description": "跟陌生人借行動電源當場充5%電，並要LINE或FB",
    "description-in": "跟陌生人借行動電源當場充5%電，並嘗試跟他要LINE或FB",
    "hardness": "困難（15分）",
    "hashtag": "#NTHUGO032",
    "id": "NTHUGO032",
    "img": "img/portfolio/032.jpg",
    "img-in": "img/portfolio/032.jpg",
    "title": "心電心"
  },
  {
    "category": "FUN 趣味",
    "condition": "截圖並上傳圖片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "到告白清大／竹大對自己告白，底下有人tag自己的話成功",
    "description-in": "到告白清大／竹大對自己告白，底下有人tag自己的話成功",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO033",
    "id": "NTHUGO033",
    "img": "img/portfolio/033.jpg",
    "img-in": "img/portfolio/033.jpg",
    "title": "自導自演"
  },
  {
    "category": "FUN 趣味",
    "condition": "錄影並上傳影片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "雙手各拿一隻掃把，大喊「西瓜榴槤斬」並開始揮舞",
    "description-in": "雙手各拿一隻掃把，大喊「西瓜榴槤斬」並開始揮舞",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO034",
    "id": "NTHUGO034",
    "img": "img/portfolio/034.jpg",
    "img-in": "img/portfolio/034.jpg",
    "title": "桐人肆尼"
  },
  {
    "category": "FUN 趣味",
    "condition": "錄影並上傳影片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "男：幫女友化妝／女：帶男友的妝出門",
    "description-in": "男：幫女友化妝／女：帶男友的妝出門",
    "hardness": "普通（10分）",
    "hashtag": "#NTHUGO035",
    "id": "NTHUGO035",
    "img": "img/portfolio/035.jpg",
    "img-in": "img/portfolio/035.jpg",
    "title": "雄兔腳撲朔、雌兔眼迷離"
  },
  {
    "category": "FUN 趣味",
    "condition": "拍照並將before/after對比圖組圖上傳至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "兩人相互交換服裝並穿出門",
    "description-in": "兩人相互交換服裝並穿出門",
    "hardness": "普通（10分）",
    "hashtag": "#NTHUGO036",
    "id": "NTHUGO036",
    "img": "img/portfolio/036.jpg",
    "img-in": "img/portfolio/036.jpg",
    "title": "換得換失"
  },
  {
    "category": "FUN 趣味",
    "condition": "錄影並上傳影片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "上課成功點到名",
    "description-in": "上課成功點到名（簽名點名：錄製簽名過程、口頭點名：錄製點到你的過程）",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO037",
    "id": "NTHUGO037",
    "img": "img/portfolio/037.jpg",
    "img-in": "img/portfolio/037.jpg",
    "title": "我有上課！"
  },
  {
    "category": "FUN 趣味",
    "condition": "拍照並上傳照片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "化熊貓妝在清大度過一天",
    "description-in": "化熊貓妝在清大度過一天",
    "hardness": "困難（15分）",
    "hashtag": "#NTHUGO038",
    "id": "NTHUGO038",
    "img": "img/portfolio/038.jpg",
    "img-in": "img/portfolio/038.jpg",
    "title": "這不是愛睏"
  },
  {
    "category": "FUN 趣味",
    "condition": "錄影並上傳影片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "拿著水木前的理髮廣告跟理髮阿姨說我要理這種的",
    "description-in": "拿著水木前的理髮廣告跟理髮阿姨說我要理這種的",
    "hardness": "普通（10分）",
    "hashtag": "#NTHUGO039",
    "id": "NTHUGO039",
    "img": "img/portfolio/039.jpg",
    "img-in": "img/portfolio/039.jpg",
    "title": "黃曉民也沒我帥"
  },
  {
    "category": "FUN 趣味",
    "condition": "拍照並上傳照片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "猜贏猜拳大賽冠軍",
    "description-in": "猜贏猜拳大賽冠軍：原科17林庭宇",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO040",
    "id": "NTHUGO040",
    "img": "img/portfolio/040.jpg",
    "img-in": "img/portfolio/040.jpg",
    "title": "拳王阿里"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "跟賀陳弘校長合照",
    "description-in": "跟賀陳弘校長合照",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO041",
    "id": "NTHUGO041",
    "img": "img/portfolio/041.jpg",
    "img-in": "img/portfolio/041-in.jpg",
    "title": "親近校長"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上，照片地點於旺宏館，需出現你們兩人與電影名稱",
    "description": "找至少一位好友在旺宏館看一場電影",
    "description-in": "找至少一位好友在旺宏館看一場電影",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO042",
    "id": "NTHUGO042",
    "img": "img/portfolio/042.jpg",
    "img-in": "img/portfolio/042.jpg",
    "title": "我有朋友"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "拿到比司多 1號 的候餐單",
    "description-in": "拿到比司多 1號 的候餐單",
    "hardness": "普通（10分）",
    "hashtag": "#NTHUGO043",
    "id": "NTHUGO043",
    "img": "img/portfolio/043.jpg",
    "img-in": "img/portfolio/043.jpg",
    "title": "叫我第一名"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "找10個社團的人一起拍照，並上傳FB列出社團名稱",
    "description-in": "找10個社團的人一起拍照，並上傳FB列出社團名稱",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO044",
    "id": "NTHUGO044",
    "img": "img/portfolio/044.jpg",
    "img-in": "img/portfolio/044.jpg",
    "title": "我有社團朋友"
  },
  {
    "category": "ISSUE 議題",
    "condition": "拍照並上傳全家福照片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "拍一張全家福",
    "description-in": "上了大學之後多久沒有好好與家人相處了呢？拍張全家福吧！",
    "hardness": "普通（10分）",
    "hashtag": "#NTHUGO045",
    "id": "NTHUGO045",
    "img": "img/portfolio/045.jpg",
    "img-in": "img/portfolio/045.jpg",
    "title": "我有家人"
  },
  {
    "category": "FUN 趣味",
    "condition": "拍照並上傳照片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "在台積草坪擺出北斗七星的圖案（不限一人）",
    "description-in": "在台積草坪擺出北斗七星的圖案（不限一人）",
    "hardness": "普通（10分）",
    "hashtag": "#NTHUGO046",
    "id": "NTHUGO046",
    "img": "img/portfolio/046.jpg",
    "img-in": "img/portfolio/046.jpg",
    "title": "我是天文學家"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "上早八的課並坐第一排",
    "description-in": "上早八的課並坐第一排",
    "hardness": "普通（10分）",
    "hashtag": "#NTHUGO047",
    "id": "NTHUGO047",
    "img": "img/portfolio/047.jpg",
    "img-in": "img/portfolio/047.jpg",
    "title": "不可能的任務"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "通識課下課與全班合照",
    "description-in": "通識課下課與全班合照",
    "hardness": "普通（10分）",
    "hashtag": "#NTHUGO048",
    "id": "NTHUGO048",
    "img": "img/portfolio/048.jpg",
    "img-in": "img/portfolio/048.jpg",
    "title": "相遇就是有緣"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片／組圖至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上，照片內需包含你們兩人及卡片，卡片需超過20字（可重複解，最多重複十次，第二次後分數改為5分）",
    "description": "寫一張有誠意的卡片送給朋友，並和他合照一張",
    "description-in": "寫一張有誠意的卡片送給朋友，並和他合照一張",
    "hardness": "普通（10分）",
    "hashtag": "#NTHUGO049",
    "id": "NTHUGO049",
    "img": "img/portfolio/049.jpg",
    "img-in": "img/portfolio/049.jpg",
    "title": "禮輕情意重"
  },
  {
    "category": "FUN 趣味",
    "condition": "拍照並上傳照片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "在男／女廁前比YA並拍照（女／男）",
    "description-in": "在男／女廁前比YA並拍照（女／男）",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO050",
    "id": "NTHUGO050",
    "img": "img/portfolio/050.jpg",
    "img-in": "img/portfolio/050.jpg",
    "title": "幼稚鬼"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上，書本上有南大校區圖書館的標籤",
    "description": "到南大校區圖書館借一本書",
    "description-in": "到南大校區圖書館借一本書",
    "hardness": "普通（10分）",
    "hashtag": "#NTHUGO051",
    "id": "NTHUGO051",
    "img": "img/portfolio/051.jpg",
    "img-in": "img/portfolio/051.jpg",
    "title": "因為沒有校內代借"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片／組圖至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上，圖中可以名牌、花色等清楚辨認是不同隻校狗",
    "description": "與五隻不同校狗拍照，並組圖上傳",
    "description-in": "與五隻不同校狗拍照，並組圖上傳",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO052",
    "id": "NTHUGO052",
    "img": "img/portfolio/052.jpg",
    "img-in": "img/portfolio/052.jpg",
    "title": "校狗好麻吉"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上，照片可清楚辨認地點為光明頂",
    "description": "天黑後到光明頂自拍上傳",
    "description-in": "天黑後到光明頂自拍上傳",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO053",
    "id": "NTHUGO053",
    "img": "img/portfolio/053.jpg",
    "img-in": "img/portfolio/053.jpg",
    "title": "天黑請閉眼"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片／組圖至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "找到校園中10種不同的植物名牌",
    "description-in": "找到校園中10種不同的植物名牌",
    "hardness": "普通（10分）",
    "hashtag": "#NTHUGO054",
    "id": "NTHUGO054",
    "img": "img/portfolio/054.jpg",
    "img-in": "img/portfolio/054.jpg",
    "title": "神農嘗百草"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "錄影並上傳影片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "大聲的跟任一個打掃阿姨說謝謝",
    "description-in": "大聲的跟任一個打掃阿姨說謝謝",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO055",
    "id": "NTHUGO055",
    "img": "img/portfolio/055.jpg",
    "img-in": "img/portfolio/055.jpg",
    "title": "禮多人不怪"
  },
  {
    "category": "ISSUE 議題",
    "condition": "留言在相簿下，截圖並上傳圖片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "閱讀張貼於粉專相簿的「同婚釋憲懶人包」",
    "description-in": "閱讀張貼於粉專相簿的「同婚釋憲懶人包」，並在相簿留言處回覆相簿描述裡的問題。",
    "hardness": "困難（15分）",
    "hashtag": "#NTHUGO056",
    "id": "NTHUGO056",
    "img": "img/portfolio/056.jpg",
    "img-in": "img/portfolio/056.jpg",
    "title": "同婚釋憲懶人包"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片／組圖至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上，出示有註明生日的證件加以證明",
    "description": "找到5個與自己同星座的人合照",
    "description-in": "找到5個與自己同星座的人合照",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO057",
    "id": "NTHUGO057",
    "img": "img/portfolio/057.jpg",
    "img-in": "img/portfolio/057.jpg",
    "title": "星座配配對"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片／組圖至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "在水漫的飛鏢機玩301模式成功玩到0分",
    "description-in": "在水漫的飛鏢機玩301模式成功玩到0分",
    "hardness": "普通（10分）",
    "hashtag": "#NTHUGO058",
    "id": "NTHUGO058",
    "img": "img/portfolio/058.jpg",
    "img-in": "img/portfolio/058.jpg",
    "title": "神射手"
  },
  {
    "category": "FUN 趣味",
    "condition": "錄影並上傳影片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上，可採縮時錄影",
    "description": "一餐吃完兩份姊妹便當",
    "description-in": "一餐吃完兩份姊妹便當",
    "hardness": "普通（10分）",
    "hashtag": "#NTHUGO059",
    "id": "NTHUGO059",
    "img": "img/portfolio/059.jpg",
    "img-in": "img/portfolio/059.jpg",
    "title": "不想吃也得吃"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照打卡並傳打卡的貼文連結至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "一天內在成功湖/昆明湖/相思湖三個地點拍照打卡",
    "description-in": "一天內在成功湖/昆明湖/相思湖三個地點拍照打卡",
    "hardness": "普通（10分）",
    "hashtag": "#NTHUGO060",
    "id": "NTHUGO060",
    "img": "img/portfolio/060.jpg",
    "img-in": "img/portfolio/060.jpg",
    "title": "湖中女神"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上，以文字輔助說明",
    "description": "日行一善",
    "description-in": "日行一善",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO061",
    "id": "NTHUGO061",
    "img": "img/portfolio/061.jpg",
    "img-in": "img/portfolio/061.jpg",
    "title": "我是好人"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上，需清楚拍攝出展覽名稱",
    "description": "看一場校內的展覽",
    "description-in": "看一場校內的展覽",
    "hardness": "困難（15分）",
    "hashtag": "#NTHUGO062",
    "id": "NTHUGO062",
    "img": "img/portfolio/062.jpg",
    "img-in": "img/portfolio/062.jpg",
    "title": "洗滌心靈"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上，需清楚拍攝出講座名稱",
    "description": "聽一場校內的講座",
    "description-in": "聽一場校內的講座",
    "hardness": "困難（15分）",
    "hashtag": "#NTHUGO063",
    "id": "NTHUGO063",
    "img": "img/portfolio/063.jpg",
    "img-in": "img/portfolio/063.jpg",
    "title": "學習新知"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "註明課程名稱並撰寫100~200字心得上傳",
    "description": "旁聽一門從來沒修過的課",
    "description-in": "旁聽一門從來沒修過的課",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO064",
    "id": "NTHUGO064",
    "img": "img/portfolio/064.jpg",
    "img-in": "img/portfolio/064.jpg",
    "title": "你一定不敢"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片／組圖至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上，包含三餐、點心、消夜等使用環保餐具的照片",
    "description": "一整天採用無痕飲食",
    "description-in": "一整天採用無痕飲食（包含碗筷皆自己攜帶，不造成任何垃圾）",
    "hardness": "困難（15分）",
    "hashtag": "#NTHUGO065",
    "id": "NTHUGO065",
    "img": "img/portfolio/065.jpg",
    "img-in": "img/portfolio/065.jpg",
    "title": "吃飽不留痕跡"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片／組圖至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上，包含至少四張當天穿著畢袍的生活照",
    "description": "從早上八點到晚上八點都穿著畢業袍+領巾",
    "description-in": "從早上八點到晚上八點都穿著畢業袍+領巾",
    "hardness": "普通（10分）",
    "hashtag": "#NTHUGO066",
    "id": "NTHUGO066",
    "img": "img/portfolio/066.jpg",
    "img-in": "img/portfolio/066.jpg",
    "title": "絕不延畢"
  },
  {
    "category": "ISSUE 議題",
    "condition": "拍照並上傳照片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上。<a href=\"http://www.bigissue.tw/about\">有關於大誌</a>",
    "description": "買一本大誌雜誌",
    "description-in": "買一本大誌雜誌（離學校最近出沒據點：校門口）",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO067",
    "id": "NTHUGO067",
    "img": "img/portfolio/067.jpg",
    "img-in": "img/portfolio/067.jpg",
    "title": "一本一百"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片／組圖至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "寫一張卡片送給老師，並和老師合照一張",
    "description-in": "寫一張卡片送給老師（任課老師、導師、老闆...皆可），並和老師合照一張",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO068",
    "id": "NTHUGO068",
    "img": "img/portfolio/068.jpg",
    "img-in": "img/portfolio/068.jpg",
    "title": "謝謝老師"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "在領取區和便當合照並上傳照片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "進\"人社院便當代購合作社\"頁面訂一個便當（需領取）",
    "description-in": "進「人社院便當代購合作社」頁面訂一個便當（需領取）",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO069",
    "id": "NTHUGO069",
    "img": "img/portfolio/069.jpg",
    "img-in": "img/portfolio/069.jpg",
    "title": "不愁吃"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "發布貼文在自己的塗鴉牆，並將貼文連結發布至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "在自己塗鴉牆上發文幫校隊大專盃加油",
    "description-in": "在自己塗鴉牆上發文幫校隊大專盃加油",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO070",
    "id": "NTHUGO070",
    "img": "img/portfolio/070.jpg",
    "img-in": "img/portfolio/070.jpg",
    "title": "清大必勝！"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上，需清楚拍攝出電影名稱",
    "description": "看一場清大夜貓子電影院的電影",
    "description-in": "看一場清大夜貓子電影院的電影",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO071",
    "id": "NTHUGO071",
    "img": "img/portfolio/071.jpg",
    "img-in": "img/portfolio/071.jpg",
    "title": "真．文青"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "到行政大樓印出任一學期的成績單拍照上傳",
    "description-in": "到行政大樓印出任一學期的成績單拍照上傳",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO072",
    "id": "NTHUGO072",
    "img": "img/portfolio/072.jpg",
    "img-in": "img/portfolio/072.jpg",
    "title": "勇者無懼"
  },
  {
    "category": "FUN 趣味",
    "condition": "將報名成員清單截圖，並上傳圖片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "揪團報名參加「不服來辦DoReMi」",
    "description-in": "揪團報名參加「不服來辦DoReMi」",
    "hardness": "普通（10分）",
    "hashtag": "#NTHUGO073",
    "id": "NTHUGO073",
    "img": "img/portfolio/073.jpg",
    "img-in": "img/portfolio/073.jpg",
    "title": "板的"
  },
  {
    "category": "ISSUE 議題",
    "condition": "拍照／截圖／錄影並上傳至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "母親節將近，向媽媽表達心意吧！",
    "description-in": "母親節將近，向媽媽表達心意吧！（形式不拘，打電話、寫卡片、送禮物...等皆可）",
    "hardness": "普通（10分）",
    "hashtag": "#NTHUGO074",
    "id": "NTHUGO074",
    "img": "img/portfolio/074.jpg",
    "img-in": "img/portfolio/074.jpg",
    "title": "母親節快樂！"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片／組圖至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "與三個校內的公共藝術作品拍照",
    "description-in": "與三個校內的公共藝術作品拍照",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO075",
    "id": "NTHUGO075",
    "img": "img/portfolio/075.jpg",
    "img-in": "img/portfolio/075.jpg",
    "title": "你也懂裝置藝術？"
  },
  {
    "category": "ISSUE 議題",
    "condition": "截圖投稿畫面並上傳圖片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "到任一清大課程平台投稿一篇修課心得",
    "description-in": "到清大通識課程平台／NTHU+／ptt清大課程版投稿一篇修課心得",
    "hardness": "普通（10分）",
    "hashtag": "#NTHUGO076",
    "id": "NTHUGO076",
    "img": "img/portfolio/076.jpg",
    "img-in": "img/portfolio/076.jpg",
    "title": "好課，值得一修再修"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上（與買家合照，並以文字註明賣出的物品）",
    "description": "使用清交二手大貨倉賣出一個物品",
    "description-in": "使用清交二手大貨倉賣出一個物品",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO077",
    "id": "NTHUGO077",
    "img": "img/portfolio/077.jpg",
    "img-in": "img/portfolio/077.jpg",
    "title": "第一桶金"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照打卡並傳打卡的貼文連結至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "到八角亭、湖心亭、梅亭三個地點拍照打卡",
    "description-in": "到八角亭、湖心亭、梅亭三個地點拍照打卡",
    "hardness": "普通（10分）",
    "hashtag": "#NTHUGO078",
    "id": "NTHUGO078",
    "img": "img/portfolio/078.jpg",
    "img-in": "img/portfolio/078.jpg",
    "title": "亭亭玉立"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片／組圖至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "找到校內三個AED拍照",
    "description-in": "找到校內三個AED拍照",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO079",
    "id": "NTHUGO079",
    "img": "img/portfolio/079.jpg",
    "img-in": "img/portfolio/079.jpg",
    "title": "緊急救護專家"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片／組圖至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上，以文字說明他們來自的國家或大學",
    "description": "與三個交換生合照上傳",
    "description-in": "與三個交換生合照上傳",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO080",
    "id": "NTHUGO080",
    "img": "img/portfolio/080.jpg",
    "img-in": "img/portfolio/080.jpg",
    "title": "國民外交"
  },
  {
    "category": "FUN 趣味",
    "condition": "拍照並上傳照片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "跟Lally握手",
    "description-in": "跟Lally握手",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO081",
    "id": "NTHUGO081",
    "img": "img/portfolio/081.jpg",
    "img-in": "img/portfolio/081.jpg",
    "title": "小豬的溫柔"
  },
  {
    "category": "FUN 趣味",
    "condition": "拍照並上傳照片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "與鴿子一起自拍",
    "description-in": "與鴿子一起自拍",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO082",
    "id": "NTHUGO082",
    "img": "img/portfolio/082.jpg",
    "img-in": "img/portfolio/082.jpg",
    "title": "我以為清大鴿子不會飛"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片／組圖至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上（四人皆出示學生證的合照）",
    "description": "大一到大四的直屬一起合照",
    "description-in": "大一到大四的直屬一起合照",
    "hardness": "普通（10分）",
    "hashtag": "#NTHUGO083",
    "id": "NTHUGO083",
    "img": "img/portfolio/083.jpg",
    "img-in": "img/portfolio/083.jpg",
    "title": "我們這一家"
  },
  {
    "category": "FUN 趣味",
    "condition": "拍照／錄影並上傳照片／影片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "讓貓底的貓來蹭你",
    "description-in": "讓貓底的貓來蹭你",
    "hardness": "普通（10分）",
    "hashtag": "#NTHUGO084",
    "id": "NTHUGO084",
    "img": "img/portfolio/084.jpg",
    "img-in": "img/portfolio/084.jpg",
    "title": "奴才來了"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照／錄影並上傳照片／影片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "拍到一張清大內松鼠的照片",
    "description-in": "拍到一張清大內松鼠的照片",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO085",
    "id": "NTHUGO085",
    "img": "img/portfolio/085.jpg",
    "img-in": "img/portfolio/085.jpg",
    "title": "獐頭鼠目"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "錄影並上傳影片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "唱校歌上傳（可自行重新編曲）",
    "description-in": "唱校歌上傳（可自行重新編曲）",
    "hardness": "普通（10分）",
    "hashtag": "#NTHUGO086",
    "id": "NTHUGO086",
    "img": "img/portfolio/086.jpg",
    "img-in": "img/portfolio/086.jpg",
    "title": "校園民歌"
  },
  {
    "category": "FUN 趣味",
    "condition": "錄影並上傳影片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上，可縮時",
    "description": "從校門口跑到台積再跑回來",
    "description-in": "從校門口跑到台積再跑回來",
    "hardness": "困難（15分）",
    "hashtag": "#NTHUGO087",
    "id": "NTHUGO087",
    "img": "img/portfolio/087.jpg",
    "img-in": "img/portfolio/087.jpg",
    "title": "累死你哈哈哈"
  },
  {
    "category": "ISSUE 議題",
    "condition": "錄影並上傳影片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上，可縮時",
    "description": "乖乖地走東門的天橋，遵守交通規則你我有責",
    "description-in": "乖乖地走東門的天橋，遵守交通規則你我有責",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO088",
    "id": "NTHUGO088",
    "img": "img/portfolio/088.jpg",
    "img-in": "img/portfolio/088.jpg",
    "title": "馬路如虎口"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上，並註明是哪個校隊",
    "description": "跟至少一位校隊成員合照（對方要穿校隊的衣服）",
    "description-in": "跟至少一位校隊成員合照（對方要穿校隊的衣服）",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO089",
    "id": "NTHUGO089",
    "img": "img/portfolio/089.jpg",
    "img-in": "img/portfolio/089.jpg",
    "title": "德智體群美"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "晨泳一次（十點以前）",
    "description-in": "晨泳一次（十點以前）",
    "hardness": "普通（10分）",
    "hashtag": "#NTHUGO090",
    "id": "NTHUGO090",
    "img": "img/portfolio/090.jpg",
    "img-in": "img/portfolio/090.jpg",
    "title": "早起的蛟龍"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "錄影並上傳影片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "直播介紹這個活動和自己的系",
    "description-in": "直播介紹清華大作戰NTHUGO這個活動和自己的系（為什麼會讀這個系？當初有什麼期許？現在回想起來有落差嗎？...）",
    "hardness": "普通（10分）",
    "hashtag": "#NTHUGO091",
    "id": "NTHUGO091",
    "img": "img/portfolio/091.jpg",
    "img-in": "img/portfolio/091.jpg",
    "title": "4年前做的蠢事"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "早上八點以前和全寢室的人合照",
    "description-in": "早上八點以前和全寢室的人合照",
    "hardness": "普通（10分）",
    "hashtag": "#NTHUGO092",
    "id": "NTHUGO092",
    "img": "img/portfolio/092.jpg",
    "img-in": "img/portfolio/092.jpg",
    "title": "早安還是晚安？"
  },
  {
    "category": "ISSUE 議題",
    "condition": "錄影並上傳影片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "確實分類後在小吃部丟垃圾",
    "description-in": "確實分類後在小吃部丟垃圾",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO093",
    "id": "NTHUGO093",
    "img": "img/portfolio/093.jpg",
    "img-in": "img/portfolio/093.jpg",
    "title": "環保小尖兵"
  },
  {
    "category": "ISSUE 議題",
    "condition": "留言在相簿下，截圖並上傳圖片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "閱讀張貼於粉專相簿的「梅竹懶人包」",
    "description-in": "閱讀張貼於粉專相簿的「梅竹懶人包」，並在相簿留言處回覆相簿描述裡的問題。https://goo.gl/8wcH8m",
    "hardness": "普通（10分）",
    "hashtag": "#NTHUGO094",
    "id": "NTHUGO094",
    "img": "img/portfolio/094.jpg",
    "img-in": "img/portfolio/094.jpg",
    "title": "梅竹懶人包"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並將before/after對比圖組圖上傳至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "在水木剪一次頭髮",
    "description-in": "在水木剪一次頭髮",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO095",
    "id": "NTHUGO095",
    "img": "img/portfolio/095.jpg",
    "img-in": "img/portfolio/095.jpg",
    "title": "鼓起勇氣"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片／組圖至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "在13個系館前擺姿勢拍照",
    "description-in": "在各個系館前擺姿勢拍照（包含13個系館：工一館、化學館、化工館、工科館、生科館、醫環館、綠能館、人社館、台積館、物理館、資電館、台達館、材料館）",
    "hardness": "困難（15分）",
    "hashtag": "#NTHUGO096",
    "id": "NTHUGO096",
    "img": "img/portfolio/096.jpg",
    "img-in": "img/portfolio/096.jpg",
    "title": "時間很多"
  },
  {
    "category": "FUN 趣味",
    "condition": "拍照並上傳照片／組圖至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "在機車塔跟10個沒有收好的安全帽合照",
    "description-in": "在機車塔跟10個沒有收好的安全帽合照",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO097",
    "id": "NTHUGO097",
    "img": "img/portfolio/097.jpg",
    "img-in": "img/portfolio/097.jpg",
    "title": "小心被幹走"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片／組圖至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "找到五個不同國籍的外籍生合照",
    "description-in": "找到五個不同國籍的外籍生合照",
    "hardness": "普通（10分）",
    "hashtag": "#NTHUGO098",
    "id": "NTHUGO098",
    "img": "img/portfolio/098.jpg",
    "img-in": "img/portfolio/098.jpg",
    "title": "地球村"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "與一個梅竹賽有上場的選手拍照",
    "description-in": "與一個梅竹賽有上場的選手拍照",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO099",
    "id": "NTHUGO099",
    "img": "img/portfolio/099.jpg",
    "img-in": "img/portfolio/099.jpg",
    "title": "交兵必敗"
  },
  {
    "category": "FUN 趣味",
    "condition": "拍照並上傳照片／組圖至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "在大草皮上野餐",
    "description-in": "在大草皮上野餐",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO100",
    "id": "NTHUGO100",
    "img": "img/portfolio/100.jpg",
    "img-in": "img/portfolio/100.jpg",
    "title": "野野野野野"
  },
  {
    "category": "FUN 趣味",
    "condition": "發布貼文在自己的FB／IG，並將截圖發布至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "撰寫 I'mmat cafe 小墊子 的食記",
    "description-in": "前往 I'mmat cafe 小墊子 坐坐，吃個點心、喝杯茶，並寫下一篇簡單的食記與朋友們分享吧！",
    "hardness": "困難（15分）",
    "hashtag": "#NTHUGO101",
    "id": "NTHUGO101",
    "img": "img/portfolio/101.jpg",
    "img-in": "img/portfolio/101.jpg",
    "title": "小墊子 I'mmat cafe"
  },
  {
    "category": "FUN 趣味",
    "condition": "發布貼文在自己的FB／IG，並將截圖發布至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "撰寫 冪 La Miette Cafe 的食記",
    "description-in": "前往 冪 La Miette Cafe 坐坐，吃個點心、喝杯茶，並寫下一篇簡單的食記與朋友們分享吧！",
    "hardness": "困難（15分）",
    "hashtag": "#NTHUGO102",
    "id": "NTHUGO102",
    "img": "img/portfolio/102.jpg",
    "img-in": "img/portfolio/102.jpg",
    "title": "冪 La Miette Cafe"
  },
  {
    "category": "FUN 趣味",
    "condition": "發布貼文在自己的FB／IG，並將截圖發布至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "撰寫 Mountain House 山房 的食記",
    "description-in": "前往 Mountain House 山房 坐坐，吃個點心、喝杯茶，並寫下一篇簡單的食記與朋友們分享吧！",
    "hardness": "困難（15分）",
    "hashtag": "#NTHUGO103",
    "id": "NTHUGO103",
    "img": "img/portfolio/103.jpg",
    "img-in": "img/portfolio/103.jpg",
    "title": "山房 Mountain House"
  },
  {
    "category": "FUN 趣味",
    "condition": "發布貼文在自己的FB／IG，並將截圖發布至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "撰寫 找出口咖啡 Exit Cafe 的食記",
    "description-in": "前往 找出口咖啡 Exit Cafe 坐坐，吃個點心、喝杯茶，並寫下一篇簡單的食記與朋友們分享吧！",
    "hardness": "困難（15分）",
    "hashtag": "#NTHUGO104",
    "id": "NTHUGO104",
    "img": "img/portfolio/104.jpg",
    "img-in": "img/portfolio/104.jpg",
    "title": "找出口咖啡 Exit Cafe"
  },
  {
    "category": "FUN 趣味",
    "condition": "發布貼文在自己的FB／IG，並將截圖發布至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "撰寫 梧桐貝貝咖啡Brunch—竹北店 的食記",
    "description-in": "前往 梧桐貝貝咖啡Brunch—竹北店 坐坐，吃個點心、喝杯茶，並寫下一篇簡單的食記與朋友們分享吧！",
    "hardness": "困難（15分）",
    "hashtag": "#NTHUGO105",
    "id": "NTHUGO105",
    "img": "img/portfolio/105.jpg",
    "img-in": "img/portfolio/105.jpg",
    "title": "梧桐貝貝咖啡Brunch—竹北店"
  },
  {
    "category": "FUN 趣味",
    "condition": "活動粉專自動產生紀錄",
    "description": "完成兩個下午茶店家的親自到訪與食記分享（見內文）",
    "description-in": "完成下列任兩個店家：小墊子、冪、山房、找出口咖啡、梧桐貝貝咖啡，的親自到訪與食記分享（即破解任務101至105之中任意兩個）",
    "hardness": "困難（15分）",
    "hashtag": "#NTHUGO106",
    "id": "NTHUGO106",
    "img": "img/portfolio/106.jpg",
    "img-in": "img/portfolio/106.jpg",
    "title": "下午茶初心者"
  },
  {
    "category": "FUN 趣味",
    "condition": "活動粉專自動產生紀錄",
    "description": "完成三個下午茶店家的親自到訪與食記分享（見內文）",
    "description-in": "完成下列任三個店家：小墊子、冪、山房、找出口咖啡、梧桐貝貝咖啡，的親自到訪與食記分享（即破解任務101至105之中任意三個）",
    "hardness": "困難（15分）",
    "hashtag": "#NTHUGO107",
    "id": "NTHUGO107",
    "img": "img/portfolio/107.jpg",
    "img-in": "img/portfolio/107.jpg",
    "title": "下午茶入門級"
  },
  {
    "category": "FUN 趣味",
    "condition": "活動粉專自動產生紀錄",
    "description": "完成四個下午茶店家的親自到訪與食記分享（見內文）",
    "description-in": "完成下列任四個店家：小墊子、冪、山房、找出口咖啡、梧桐貝貝咖啡，的親自到訪與食記分享（即破解任務101至105之中任意四個）",
    "hardness": "困難（15分）",
    "hashtag": "#NTHUGO108",
    "id": "NTHUGO108",
    "img": "img/portfolio/108.jpg",
    "img-in": "img/portfolio/108.jpg",
    "title": "下午茶進階玩家"
  },
  {
    "category": "FUN 趣味",
    "condition": "活動粉專自動產生紀錄",
    "description": "完成五個下午茶店家的親自到訪與食記分享（見內文）",
    "description-in": "完成下列共五個店家：小墊子、冪、山房、找出口咖啡、梧桐貝貝咖啡，的親自到訪與食記分享（即破解任務101至105）",
    "hardness": "困難（15分）",
    "hashtag": "#NTHUGO109",
    "id": "NTHUGO109",
    "img": "img/portfolio/109.jpg",
    "img-in": "img/portfolio/109.jpg",
    "title": "下午茶達人"
  },
  {
    "category": "ISSUE 議題",
    "condition": "分享影片、回答<a href=\"https://www.youtube.com/watch?v=BDHVGtpnKNQ&amp;feature=youtu.be\">影片</a>下方問題在自己的FB塗鴉牆，截圖並上傳圖片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上。",
    "description": "觀看小墊子老闆／清大電機99級林峻寬學長的小專訪",
    "description-in": "看完小墊子 I'mmat cafe 老闆 —— 清大電機99級 林峻寬 學長 的小專訪，並回答影片貼文裡的問題",
    "hardness": "困難（15分）",
    "hashtag": "#NTHUGO110",
    "id": "NTHUGO110",
    "img": "img/portfolio/110.jpg",
    "img-in": "img/portfolio/110.jpg",
    "title": "不聽學長言，吃虧在眼前"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並照片／組圖搭配文字，上傳至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "介紹自己的社團",
    "description-in": "介紹自己的社團，分享校園生活中，自己從社團學習到了什麼",
    "hardness": "普通（10分）",
    "hashtag": "#NTHUGO111",
    "id": "NTHUGO111",
    "img": "img/portfolio/111.jpg",
    "img-in": "img/portfolio/111.jpg",
    "title": "我的社團"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並照片／組圖搭配文字，上傳至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "分享自己的系隊",
    "description-in": "分享一張系隊練習或比賽的照片，並介紹自己當初加入的原因，系隊對你來說的意義",
    "hardness": "普通（10分）",
    "hashtag": "#NTHUGO112",
    "id": "NTHUGO112",
    "img": "img/portfolio/112.jpg",
    "img-in": "img/portfolio/112.jpg",
    "title": "我的系隊"
  },
  {
    "category": "ISSUE 議題",
    "condition": "拍照並照片／組圖搭配文字，上傳至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "在圖書館找到並閱讀一本與性別議題相關的書籍",
    "description-in": "在圖書館找到並閱讀一本與性別議題相關的書籍，分享給大家",
    "hardness": "困難（15分）",
    "hashtag": "#NTHUGO113",
    "id": "NTHUGO113",
    "img": "img/portfolio/113.jpg",
    "img-in": "img/portfolio/113.jpg",
    "title": "性別不簡單"
  },
  {
    "category": "ISSUE 議題",
    "condition": "留言在相簿下，截圖並上傳圖片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "閱讀張貼於粉專相簿的「校歌懶人包」",
    "description-in": "閱讀張貼於粉專相簿的「校歌懶人包」，並在相簿留言處回覆相簿描述裡的問題。",
    "hardness": "普通（10分）",
    "hashtag": "#NTHUGO114",
    "id": "NTHUGO114",
    "img": "img/portfolio/114.jpg",
    "img-in": "img/portfolio/114.jpg",
    "title": "校歌懶人包"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "截圖並上傳圖片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "上傳一段自己展現個人技1分鐘的影片並獲得50讚",
    "description-in": "上傳一段自己展現個人技1分鐘的影片並獲得50讚",
    "hardness": "普通（10分）",
    "hashtag": "#NTHUGO115",
    "id": "NTHUGO115",
    "img": "img/portfolio/115.jpg",
    "img-in": "img/portfolio/115.jpg",
    "title": "魅力發散"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "截圖報名頁面，並上傳圖片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "報名參加畢聯會舉辦的舞會【一期一會】",
    "description-in": "報名參加畢聯會舉辦的舞會【一期一會】",
    "hardness": "普通（10分）",
    "hashtag": "#NTHUGO116",
    "id": "NTHUGO116",
    "img": "img/portfolio/116.jpg",
    "img-in": "img/portfolio/116.jpg",
    "title": "最後一支舞"
  },
  {
    "category": "ISSUE 議題",
    "condition": "發布貼文在自己的塗鴉牆，並將貼文連結發布至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "找尋3則重大國際新聞",
    "description-in": "找尋3則重大國際新聞，並打50-100字的摘要後連同新聞連結發到自己塗鴉牆上",
    "hardness": "困難（15分）",
    "hashtag": "#NTHUGO117",
    "id": "NTHUGO117",
    "img": "img/portfolio/117.jpg",
    "img-in": "img/portfolio/117.jpg",
    "title": "關心世界"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "在表演現場拍照並上傳照片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "參加任意系所的之夜或者畢業公演",
    "description-in": "參加任意系所的之夜或者畢業公演",
    "hardness": "普通（10分）",
    "hashtag": "#NTHUGO118",
    "id": "NTHUGO118",
    "img": "img/portfolio/118.jpg",
    "img-in": "img/portfolio/118.jpg",
    "title": "夜總會"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍收據／購買證明並上傳照片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "預購／購買任意友周的商品",
    "description-in": "預購／購買任意友周的商品",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO119",
    "id": "NTHUGO119",
    "img": "img/portfolio/119.jpg",
    "img-in": "img/portfolio/119.jpg",
    "title": "美食大王"
  },
  {
    "category": "ISSUE 議題",
    "condition": "發布貼文在活動頁面",
    "description": "寫出自己的座右銘並說明原因",
    "description-in": "寫出自己的座右銘並說明原因",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO120",
    "id": "NTHUGO120",
    "img": "img/portfolio/120.jpg",
    "img-in": "img/portfolio/120.jpg",
    "title": "座右銘"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "description-in": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO121",
    "id": "NTHUGO121",
    "img": "img/portfolio/121.jpg",
    "img-in": "img/portfolio/121-in.jpg",
    "title": "神祕地點01"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "description-in": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "hardness": "普通（10分）",
    "hashtag": "#NTHUGO122",
    "id": "NTHUGO122",
    "img": "img/portfolio/122.jpg",
    "img-in": "img/portfolio/122-in.jpg",
    "title": "神祕地點02"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "description-in": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO123",
    "id": "NTHUGO123",
    "img": "img/portfolio/123.jpg",
    "img-in": "img/portfolio/123-in.jpg",
    "title": "神祕地點03"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "description-in": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "hardness": "普通（10分）",
    "hashtag": "#NTHUGO124",
    "id": "NTHUGO124",
    "img": "img/portfolio/124.jpg",
    "img-in": "img/portfolio/124-in.jpg",
    "title": "神祕地點04"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "description-in": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "hardness": "普通（10分）",
    "hashtag": "#NTHUGO125",
    "id": "NTHUGO125",
    "img": "img/portfolio/125.jpg",
    "img-in": "img/portfolio/125-in.jpg",
    "title": "神祕地點05"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "description-in": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "hardness": "普通（10分）",
    "hashtag": "#NTHUGO126",
    "id": "NTHUGO126",
    "img": "img/portfolio/126.jpg",
    "img-in": "img/portfolio/126-in.jpg",
    "title": "神祕地點06"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "description-in": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "hardness": "普通（10分）",
    "hashtag": "#NTHUGO127",
    "id": "NTHUGO127",
    "img": "img/portfolio/127.jpg",
    "img-in": "img/portfolio/127-in.jpg",
    "title": "神祕地點07"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "description-in": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO128",
    "id": "NTHUGO128",
    "img": "img/portfolio/128.jpg",
    "img-in": "img/portfolio/128-in.jpg",
    "title": "神祕地點08"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "description-in": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO129",
    "id": "NTHUGO129",
    "img": "img/portfolio/129.jpg",
    "img-in": "img/portfolio/129-in.jpg",
    "title": "神祕地點09"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "description-in": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO130",
    "id": "NTHUGO130",
    "img": "img/portfolio/130.jpg",
    "img-in": "img/portfolio/130-in.jpg",
    "title": "神祕地點10"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "description-in": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "hardness": "困難（15分）",
    "hashtag": "#NTHUGO131",
    "id": "NTHUGO131",
    "img": "img/portfolio/131.jpg",
    "img-in": "img/portfolio/131-in.jpg",
    "title": "神祕地點11"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "description-in": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO132",
    "id": "NTHUGO132",
    "img": "img/portfolio/132.jpg",
    "img-in": "img/portfolio/132-in.jpg",
    "title": "神祕地點12"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "description-in": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO133",
    "id": "NTHUGO133",
    "img": "img/portfolio/133.jpg",
    "img-in": "img/portfolio/133-in.jpg",
    "title": "神祕地點13"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "description-in": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "hardness": "困難（15分）",
    "hashtag": "#NTHUGO134",
    "id": "NTHUGO134",
    "img": "img/portfolio/134.jpg",
    "img-in": "img/portfolio/134-in.jpg",
    "title": "神祕地點14"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "description-in": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "hardness": "困難（15分）",
    "hashtag": "#NTHUGO135",
    "id": "NTHUGO135",
    "img": "img/portfolio/135.jpg",
    "img-in": "img/portfolio/135-in.jpg",
    "title": "神祕地點15"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "description-in": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "hardness": "困難（15分）",
    "hashtag": "#NTHUGO136",
    "id": "NTHUGO136",
    "img": "img/portfolio/136.jpg",
    "img-in": "img/portfolio/136-in.jpg",
    "title": "神祕地點16"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "description-in": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "hardness": "普通（10分）",
    "hashtag": "#NTHUGO137",
    "id": "NTHUGO137",
    "img": "img/portfolio/137.jpg",
    "img-in": "img/portfolio/137-in.jpg",
    "title": "神祕地點17"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "description-in": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "hardness": "普通（10分）",
    "hashtag": "#NTHUGO138",
    "id": "NTHUGO138",
    "img": "img/portfolio/138.jpg",
    "img-in": "img/portfolio/138-in.jpg",
    "title": "神祕地點18"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "description-in": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO139",
    "id": "NTHUGO139",
    "img": "img/portfolio/139.jpg",
    "img-in": "img/portfolio/139-in.jpg",
    "title": "神祕地點19"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "description-in": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO140",
    "id": "NTHUGO140",
    "img": "img/portfolio/140.jpg",
    "img-in": "img/portfolio/140-in.jpg",
    "title": "神祕地點20"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "description-in": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO141",
    "id": "NTHUGO141",
    "img": "img/portfolio/141.jpg",
    "img-in": "img/portfolio/141-in.jpg",
    "title": "神祕地點21"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "description-in": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO142",
    "id": "NTHUGO142",
    "img": "img/portfolio/142.jpg",
    "img-in": "img/portfolio/142-in.jpg",
    "title": "神祕地點22"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "description-in": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "hardness": "普通（10分）",
    "hashtag": "#NTHUGO143",
    "id": "NTHUGO143",
    "img": "img/portfolio/143.jpg",
    "img-in": "img/portfolio/143-in.jpg",
    "title": "神祕地點23"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片至粉專開的<a href=\"https://www.facebook.com/events/118086895417511/\">活動頁面</a>上",
    "description": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "description-in": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO144",
    "id": "NTHUGO144",
    "img": "img/portfolio/144.jpg",
    "img-in": "img/portfolio/144-in.jpg",
    "title": "神祕地點24"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片至粉專開的活動頁面上",
    "description": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "description-in": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "hardness": "普通（10分）",
    "hashtag": "#NTHUGO145",
    "id": "NTHUGO145",
    "img": "img/portfolio/145.jpg",
    "img-in": "img/portfolio/145-in.jpg",
    "title": "神祕地點25"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片至粉專開的活動頁面上",
    "description": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "description-in": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "hardness": "普通（10分）",
    "hashtag": "#NTHUGO146",
    "id": "NTHUGO146",
    "img": "img/portfolio/146.jpg",
    "img-in": "img/portfolio/146-in.jpg",
    "title": "神祕地點26"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片至粉專開的活動頁面上",
    "description": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "description-in": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO147",
    "id": "NTHUGO147",
    "img": "img/portfolio/147.jpg",
    "img-in": "img/portfolio/147-in.jpg",
    "title": "神祕地點27"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片至粉專開的活動頁面上",
    "description": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "description-in": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "hardness": "普通（10分）",
    "hashtag": "#NTHUGO148",
    "id": "NTHUGO148",
    "img": "img/portfolio/148.jpg",
    "img-in": "img/portfolio/148-in.jpg",
    "title": "神祕地點28"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片至粉專開的活動頁面上",
    "description": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "description-in": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "hardness": "困難（15分）",
    "hashtag": "#NTHUGO149",
    "id": "NTHUGO149",
    "img": "img/portfolio/149.jpg",
    "img-in": "img/portfolio/149-in.jpg",
    "title": "神祕地點29"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片至粉專開的活動頁面上",
    "description": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "description-in": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "hardness": "普通（10分）",
    "hashtag": "#NTHUGO150",
    "id": "NTHUGO150",
    "img": "img/portfolio/150.jpg",
    "img-in": "img/portfolio/150-in.jpg",
    "title": "神祕地點30"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片至粉專開的活動頁面上",
    "description": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "description-in": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO151",
    "id": "NTHUGO151",
    "img": "img/portfolio/151.jpg",
    "img-in": "img/portfolio/151-in.jpg",
    "title": "神祕地點31"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片至粉專開的活動頁面上",
    "description": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "description-in": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "hardness": "普通（10分）",
    "hashtag": "#NTHUGO152",
    "id": "NTHUGO152",
    "img": "img/portfolio/152.jpg",
    "img-in": "img/portfolio/152-in.jpg",
    "title": "神祕地點32"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "拍照並上傳照片至粉專開的活動頁面上",
    "description": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "description-in": "找到圖片中的地點，並和圖中人物擺出一樣的姿勢拍照",
    "hardness": "普通（10分）",
    "hashtag": "#NTHUGO153",
    "id": "NTHUGO153",
    "img": "img/portfolio/153.jpg",
    "img-in": "img/portfolio/153-in.jpg",
    "title": "神祕地點33"
  },
  {
    "category": "FUN 趣味",
    "condition": "粉專自動產生紀錄",
    "description": "邀請5個還沒有報名的朋友，帶領他們獲得20分！",
    "description-in": "邀請 5 個還沒有報名的朋友，請他們在報名表單新增的欄位「推薦人」中填入你的FB名字，並帶領他們獲得 20 分！",
    "hardness": "普通（10分）",
    "hashtag": "#NTHUGO154",
    "id": "NTHUGO154",
    "img": "img/portfolio/154.jpg",
    "img-in": "img/portfolio/154.jpg",
    "title": "我的快樂夥伴"
  },
  {
    "category": "FUN 趣味",
    "condition": "粉專自動產生紀錄",
    "description": "接受「推薦人」的邀請，加入活動並獲得20分！",
    "description-in": "接受「推薦人」的邀請，加入活動並獲得20分，讓他們明白大學生在（抽獎）deadline前的潛力無窮！",
    "hardness": "困難（15分）",
    "hashtag": "#NTHUGO155",
    "id": "NTHUGO155",
    "img": "img/portfolio/155.jpg",
    "img-in": "img/portfolio/155.jpg",
    "title": "不鳴則已，一鳴驚人"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "截圖選書平台選書完成的圖片，並上傳至粉專開的活動頁面上",
    "description": "加入圖書館的「清愛的！BOOK忘我」活動，傳遞祝福給學弟妹吧！",
    "description-in": "加入圖書館的「清愛的！BOOK忘我」活動，把畢業生的祝福藏在書中，傳遞給學弟妹吧！",
    "hardness": "困難（15分）",
    "hashtag": "#NTHUGO156",
    "id": "NTHUGO156",
    "img": "img/portfolio/156.jpg",
    "img-in": "img/portfolio/156-in.jpg",
    "title": "清愛的！BOOK忘我"
  },
  {
    "category": "FUN 趣味",
    "condition": "截圖並上傳圖片至粉專開的活動頁面上",
    "description": "邀請同學參加5/17的辦桌，並被不同的人打槍 5 次",
    "description-in": "用ＦＢ密同學邀請他們參加 5/17 的「不服來辦DoReMi」（辦桌），並被不同的人打槍 5 次",
    "hardness": "普通（10分）",
    "hashtag": "#NTHUGO157",
    "id": "NTHUGO157",
    "img": "img/portfolio/157.jpg",
    "img-in": "img/portfolio/157.jpg",
    "title": "一個人的桌菜"
  },
  {
    "category": "CAMPUS 校園",
    "condition": "分享粉專的校友證專文簡介，內文打上「清華黨證在手，校友希望無窮」並按讚+tag<a href=\"https://www.facebook.com/nthualumni/\">校友服務中心粉專</a>。截圖「分享NTHUGO粉專貼文」及「按讚校友服務中心粉專」兩張圖片上傳活動頁面。",
    "description": "黨證在手，暢行無阻，清大校友證就是你的首選！",
    "description-in": "黨證在手，暢行無阻。你還在想黨證怎麼拿嗎？不用想了，清大校友證就是你的首選！",
    "hardness": "普通（10分）",
    "hashtag": "#NTHUGO158",
    "id": "NTHUGO158",
    "img": "img/portfolio/158.jpg",
    "img-in": "img/portfolio/158.jpg",
    "title": "尊爵不凡清華黨"
  },
  {
    "category": "FUN 趣味",
    "condition": "前往<a href=\"https://www.facebook.com/novahc/?fref=ts\">NOVA新竹店</a>，打卡並Hashtag #NOVA新竹店，截圖上傳至粉專活動頁面。（畢聯會與NOVA合作，只要打卡即可至服務台領取USB小電扇喔！）",
    "description": "前往NOVA打卡，免費拿小禮物，學習做個好工具人！",
    "description-in": "想成為工具人的第一步，就是要熟悉電腦各種配備。來NOVA打卡好好學習吧！還可以到服務台免費領取USB風扇喔！",
    "hardness": "普通（10分）",
    "hashtag": "#NTHUGO159",
    "id": "NTHUGO159",
    "img": "img/portfolio/159.jpg",
    "img-in": "img/portfolio/159.jpg",
    "title": "NOVA"
  },
  {
    "category": "ISSUE 議題",
    "condition": "填寫<a href=\"http://affairs.web.nthu.edu.tw/files/14-1011-118220,r127-1.php?Lang=zh-tw\">小吃部統包商杏一及7-11續約評鑑</a>（5/3～5/10），上傳問卷填寫確認信的截圖至粉專活動頁面",
    "description": "麥當當的死活！？小七的存亡！？就靠你拯救！",
    "description-in": "小吃部的去留！？麥當當的死活！？小七的存亡！？就靠你拯救了！！！",
    "hardness": "簡單（5分）",
    "hashtag": "#NTHUGO160",
    "id": "NTHUGO160",
    "img": "img/portfolio/160.jpg",
    "img-in": "img/portfolio/160.jpg",
    "title": "小吃部求救中"
  }
];
